### ISSUE TITLE
cant compile

### ISSUE THREAD

**Issue by 0x90h** [theorywrong/OpenRTE#2]
i have virgin PS4SDK 

clang-5.0  -c source/server.c -std=c11 -O3 -Wall -pedantic -m64 -mcmodel=large -Wno-zero-length-array -Wno-format-pedantic -I. -Iinclude  -ffreestanding -nostdlib -nostdinc -fno-builtin -fno-stack-protector -D__PS4__ -I/usr/local/ps4dev/ps4sdk/include -I /usr/local/ps4dev/ps4sdk/include/sce -target x86_64-scei-ps4 -fPIE -o build/server.c.o
/usr/local/ps4dev/ps4sdk/make/ps4sdk.mk:157: recipe for target 'build/server.c.o' failed
In file included from source/server.c:28:
In file included from /usr/local/ps4dev/ps4sdk/include/pthread.h:46:
/usr/local/ps4dev/ps4sdk/include/sched.h:145:2: error: use of undeclared identifier 'curthread'
        curthread->td_pinned++;
        ^
/usr/local/ps4dev/ps4sdk/include/sched.h:151:2: error: use of undeclared identifier 'curthread'
        curthread->td_pinned--;
        ^
In file included from source/server.c:31: 
----------------------
same error in 

make: *** [build/server.c.o] Error 1
In file included from source/openrte.c:29:
In file included from /usr/local/ps4dev/ps4sdk/include/pthread.h:46:
/usr/local/ps4dev/ps4sdk/include/sched.h:145:2: error: use of undeclared identifier 'curthread'
        curthread->td_pinned++;
        ^
/usr/local/ps4dev/ps4sdk/include/sched.h:151:2: error: use of undeclared identifier 'curthread'
        curthread->td_pinned--;
        ^
In file included from source/openrte.c:35:

**Comment by theorywrong** [comment]
https://github.com/freebsd/freebsd/blob/master/sys/sys/sched.h
add this to /usr/local/ps4dev/ps4sdk/include/ 👍

**Comment by theorywrong** [comment]
I should have taken the time to read the error, sorry xP
i have checking my sched.h:
https://ghostbin.com/paste/d78ms

my sched.h doesn't have any curthead (different of https://github.com/freebsd/freebsd/blob/master/sys/sys/sched.h)

Use this instead
